ignore:
  - ".*/config/.*"  # ignore folders and all its contents
  - ".*/entity/.*" # ignore folders and all its contents
  - ".*/ApplicationConfig.java"
  - ".*/WebConfig.java"
  - "**/data/tm/*"
  - "**/legacy_ingest/*"
  - "**/dto/*"
  