language: java
jdk: oraclejdk8
services:
- docker
script:
- "./gradlew check --info"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    - SPRING_PROFILES_ACTIVE=default,integration-tests
    - secure: fD+2/XSJLE063/14YLXEKD2PqT5nanNeFZcBuQXSxTl5VpQRuQf3Kk1sVwjIFNtwCLESfikIYDFoTnmoW9GXvMrweMp4G3+D2vb/f3a4LajKg8G29C4+Tdkqe2OquUoc6xt08XhjoH+vEUWmNXZJUlFYCkcnEOdS6WP7xg1ODiiTVNHde6LcgE2ReDy+/nXrQIDhiGG1FV75ztLBwmC1YdldyyiOYxGJqi50SdTX+S3he+J7ZcnsgnB9kpoFvz5gI5maCUzSyJ1FwxDH6iyynl9qDsa9JGnCg4Iip7xtt9XJnVaNfSNou2K5DBa90uG65/j+qhTTB2P/+6hxbe/dKsTZjBayMAEl9Q7L1ZzOz7AbYQKreCeAFOyygXUWUU4q5hVH6YSnabmFqtJItPuS+lkE8zngRis26GC3pmZkfa4MnKGnXcXbji22zh0r2BBwgKsyLHkPPnrCZKtAEA699h5SGXswSjes0q51ARiuHFIvAoD3b8O9ZP4IATcOqXkWp/faXx2iqqan2eonnADsCXFbZf+63kfsmFr8yvYUeaSFQeAS/KiV2kf1Py6RnsxZApUah/aNJrySi74Rx9bPbEIP6r/2Z1N8AYxbcyFLih9NcHeVdbTjpv6iVg4btpJ/uHMtE7mqb/Kp58NyExQrn9XqbJpjopdT3kYHwCjeU2w=
    - secure: tA70irioDQY346/id+12Tdo/1BXY589oQMFbyxaqWve88cq2M0pHKY/JfEOVKIScrZcY3+pSduNdkVKb9Xf6O0e/QoBSdCTKj56x8ZTFEmmjFe20KHeYUvSOO820cPVFD5OCFGqHO5rvJJjuOZncPXEu08KcnGUmLuBlbVqC9O0suMH47xHPSFWnl/fH1LPSRzBAGhqKQVmpvnKwuXF4+5X/dTHYfqVRxKsZqfN64+fx7hut+IbVimPGLeUESrhMtCpGww+yQDO9/88SwG8zdWR+l7HELPeT/Z8qkvgM4ManaNXW2aIkrmLYQ7lIDFW8h5i05QG0URVR5jKTyGpSQrIJHGIi7ROw3aZCp237cB1QowVnaZcqKXNWQHRQSq8/+OCHyItb7qXs3UuVINa7Xd3x/8Kp6PqP8UVAvBMSkcHb9A4HBKdi34+CkzdJPr5FygzzJDAe6rg6v8nG6AXOswxOrUMei8DH4a4e8cLcRjeLRwCLMrV1abJyldJ/4VhSCr6pwJctcwkXyiaAXj2HIoQabw0G5hlLyY18CIBOqYIzufUeQp9U1vm4SvKpOjNtGINw51uD9V6P5f/4c9YZxjfLLeeGvXSjR+/Beo5KgnTnjkkcY0eecHNWd2V5EaszXVVndBufY3vyZA2B9osIN6EVOai7z8CCKYapjMcEs04=
branches:
  only:
  - master
notifications:
  slack:
    secure: 0WJDUOhUvPt3Yu7xuyoMTNO9GXFKYAfYd1bRsRmjPfeeozvcXuKPAchCMVClNkmkaWZd/JrY/sW/pENQY3lMxx95g2TAIbgeZ4r2pUE3U22Ee3Zrdv0JB40kYoXEyVhjk9cB5zMdNvI/fBuN6eByYvl+CMI72fQHcFLgshXNMOO5RGnEFA5SAQM3qTmNGpXhQ+1hc35SadqBZCXz3h5v9eE2tHn55FDs73UljKXPbqMbaJb8HcFd7pV1Ibdjzmb9HPKqkCFxgJXdKHJz8fsO1BspZ2BxN/c+EXR/utmPXuUdJKZUtqAKIVEnRyrJ8+299kqGO/53xVm94pwZK+tHpV8+qJqhihuxQ1QMRbCC9bUMKU2H964jpYDh53Y1lP0vKO5BrMDo+pSR0CQj49gnwZR6dJFJjhd+Zjb+R0c5vHzfLLerXK5k+THLORSxTxY/iIjj5zS4sjW+61aPKbRKL4ZJH18lJtpoXDjWhOGPQdoPk2xLamGmwXQ76haK2I98WYeJjGA1yjlfrpZeTSq7rNgaPId2Lhsl7mmWTRQ9rFLErv4mLuoLq5BZuiHtFButjYomAMqIDP3q1RvzilA2j6XS8huH8Ygb8ne6HPDrpVHCpavUCxQ/yehpb3/bPIuuUXR/2qdeTymNgU7RNSQ4EOn6M7bNZGkqtLv4eStlcMM=
after_script:
  - if [ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" == "false" ];
    then echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
    docker build -t fwmtjobsvc --build-arg jar=build/libs/fwmt-job-service-1.0.0.jar .;
    docker tag fwmtjobsvc sdcplatform/fwmtjobsvc:$TRAVIS_BUILD_NUMBER;
    docker push sdcplatform/fwmtjobsvc;
    fi
