
language: java
jdk: oraclejdk8

services:
  - docker

#cache:
#  directories:
#  - $HOME/.cache
#

script: 
  - "./gradlew check"

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  - "SPRING_PROFILES_ACTIVE=default,integration-tests"

branches:
  only:
    - master