language: java
jdk: oraclejdk8
services:
- docker
script:
- "./gradlew check --info"
after_success:
- bash <(curl -s https://codecov.io/bash)
after_failure:
- if [ -f build/fwmt-service-mocks.log ]; then cat build/fwmt-service-mocks.log; fi
- if [ -f build/fwmt-service-mocks-errors.log ]; then cat build/fwmt-service-mocks-errors.log; fi
env:
  global:
    - SPRING_PROFILES_ACTIVE=default,integration-tests
    - secure: fD+2/XSJLE063/14YLXEKD2PqT5nanNeFZcBuQXSxTl5VpQRuQf3Kk1sVwjIFNtwCLESfikIYDFoTnmoW9GXvMrweMp4G3+D2vb/f3a4LajKg8G29C4+Tdkqe2OquUoc6xt08XhjoH+vEUWmNXZJUlFYCkcnEOdS6WP7xg1ODiiTVNHde6LcgE2ReDy+/nXrQIDhiGG1FV75ztLBwmC1YdldyyiOYxGJqi50SdTX+S3he+J7ZcnsgnB9kpoFvz5gI5maCUzSyJ1FwxDH6iyynl9qDsa9JGnCg4Iip7xtt9XJnVaNfSNou2K5DBa90uG65/j+qhTTB2P/+6hxbe/dKsTZjBayMAEl9Q7L1ZzOz7AbYQKreCeAFOyygXUWUU4q5hVH6YSnabmFqtJItPuS+lkE8zngRis26GC3pmZkfa4MnKGnXcXbji22zh0r2BBwgKsyLHkPPnrCZKtAEA699h5SGXswSjes0q51ARiuHFIvAoD3b8O9ZP4IATcOqXkWp/faXx2iqqan2eonnADsCXFbZf+63kfsmFr8yvYUeaSFQeAS/KiV2kf1Py6RnsxZApUah/aNJrySi74Rx9bPbEIP6r/2Z1N8AYxbcyFLih9NcHeVdbTjpv6iVg4btpJ/uHMtE7mqb/Kp58NyExQrn9XqbJpjopdT3kYHwCjeU2w=
    - secure: tA70irioDQY346/id+12Tdo/1BXY589oQMFbyxaqWve88cq2M0pHKY/JfEOVKIScrZcY3+pSduNdkVKb9Xf6O0e/QoBSdCTKj56x8ZTFEmmjFe20KHeYUvSOO820cPVFD5OCFGqHO5rvJJjuOZncPXEu08KcnGUmLuBlbVqC9O0suMH47xHPSFWnl/fH1LPSRzBAGhqKQVmpvnKwuXF4+5X/dTHYfqVRxKsZqfN64+fx7hut+IbVimPGLeUESrhMtCpGww+yQDO9/88SwG8zdWR+l7HELPeT/Z8qkvgM4ManaNXW2aIkrmLYQ7lIDFW8h5i05QG0URVR5jKTyGpSQrIJHGIi7ROw3aZCp237cB1QowVnaZcqKXNWQHRQSq8/+OCHyItb7qXs3UuVINa7Xd3x/8Kp6PqP8UVAvBMSkcHb9A4HBKdi34+CkzdJPr5FygzzJDAe6rg6v8nG6AXOswxOrUMei8DH4a4e8cLcRjeLRwCLMrV1abJyldJ/4VhSCr6pwJctcwkXyiaAXj2HIoQabw0G5hlLyY18CIBOqYIzufUeQp9U1vm4SvKpOjNtGINw51uD9V6P5f/4c9YZxjfLLeeGvXSjR+/Beo5KgnTnjkkcY0eecHNWd2V5EaszXVVndBufY3vyZA2B9osIN6EVOai7z8CCKYapjMcEs04=
branches:
  only:
  - master
notifications:
  slack:
    secure: LOijmxW75uH1cFuZgQ2tTZZvbBSaUaWcHxI4tubibCM1LJCcEJOSYPi8MxVi0nLU6XHSQfCVPGI6D4TiFUq8oAPrTqO1wwuV3KWwgAxsdC3bmWNWE3jpbzb2WMKp41E+qN2iMoOZh/egQWGSYb5DfdaR7iAn4+Z+2Bx0gRLthmvOiYPyeB1X6WmVKvjvC9Znpt6JowmGaCgdWSdp7VpIuNqimFJvvDFvY/Oc/n9b1nWjcfr4D/EVgtGK14IpTIyj/yLkAiIX4GkBUNmNBRxjopZlhXCoHhi6B48ECQJf94g8/OYcCkxHEWZrdoEiqmojE639BMYfAgk621JLWsyEGb30sccJLHOwlOhsd76peMQ6DP6j5/1mQdnWT4Mb+jSVnifiDhWdkPisMKwm3b97trxk+t/3ySkiICVeiruLfCsK9SHP172BdpYi9L7Qj3H7uO6CXaDTRhKkfsmI1c/cWmKqpu2MpRko4NZYAwethaIBSM+r5oxfvf10974G2S7EMPwxvI6oYUF82jzg3xLAJItQqk5VMHv8yGSzl9DEDohWwQQOgtDnZxCzg2n818uFxxGdwF0zrW+W62HIoklPsQEGsCZXoto4KV8+sl3F4VBC332mY4QhmpgB15wS2k9B4UIkAMFv9cfXQo9qZXCXFo6uU014sF7qpvENKW76+TY=
after_script:
  - if [ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" == "false" ];
    then echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
    docker build -t fwmtjobsvc --build-arg jar=build/libs/fwmt-job-service-1.0.0.jar .;
    docker tag fwmtjobsvc sdcplatform/fwmtjobsvc:$TRAVIS_BUILD_NUMBER;
    docker push sdcplatform/fwmtjobsvc;
    fi
