info:
  #name: @project.artifactId@
  #version: @project.version@
  #origin: @scm.url@
  #commit: @buildNumber@
  #branch: @scmBranch@
  #built: @timestamp@

spring:
  application:
    name: fwmt-job-service

# The following data is sensitive and must not be shared
totalmobile:
  username: username
  password: password
  url: "https://ons.totalmobile.co.uk"
  message-queue-path: "/Live/Services/TM/v20/Messaging/MessageQueueWs.asmx"
  namespace: "http://schemas.consiliumtechnologies.com/wsdl/mobile/2007/07/messaging/"
security.user:
  name: name
  password: password

