info:
  name: @project.artifactId@
  version: @project.version@
  origin: @scm.url@
  commit: @buildNumber@
  branch: @scmBranch@
  built: @timestamp@

server:
  contextPath: /jobs
  port: 9091

spring:
  application:
    name: fwmt-job-service
  http.multipart:
    max-file-size: 12800MB
    max-request-size: 12800MB
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:postgresql://localhost/postgres?currentSchema=gateway
    driver-class-name: org.postgresql.Driver
    schema: classpath:/schema.sql
    continue-on-error: false
    username: postgres
    password: postgres

liquibase:
  url: jdbc:postgresql://localhost:5432/postgres?currentSchema=gateway
  default-schema: gateway
  change-log: classpath:db/changelog/db.changelog-master.yml
  user: postgres
  password: postgres

management.endpoint.health.show-details: always

logging:
  level:
    root: WARN
    uk.gov.ons.fwmt: DEBUG
    org.springframework.security: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.apache.commons.dbcp2: ERROR
  file: target/SpringErrors/spring.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{100} - %msg%n"
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{100} - %msg%n"

security.user:
  name: "user"
  password: "password"

totalmobile:
  username: ""
  password: ""
  url: ""
  message-queue-path: "/Services/TM/v20/Messaging/MessageQueueWs.asmx"
  message-queue-wsdl-path: "src/main/resources/wsdl/Messaging_MessageQueueWs.wsdl"
  message-queue-namespace: "http://schemas.consiliumtechnologies.com/wsdl/mobile/2007/07/messaging/"
  message-queue-package: "com.consiliumtechnologies.schemas.services.mobile._2009._03.messaging"
  outgoing-ws-namespace: "http://schemas.consiliumtechnologies.com/services/mobile/2009/03/messaging"
  web:
    login-url: "/WebAdmin/Login"
    save-user-url: "/WebAdmin/Administration/Users/SaveUser"

service:
  resource:
    username: "user"
    password: "password"
    baseUrl: "http://localhost:9093/resources"
    operation:
      users:
        find:
          path: "/users/auth/{authNo}"
        findAlt:
          path: "/users/alternative/{altAuthNo}"
      jobs:
        find:
          path: "/jobs/{authNo}"
        create:
          path: "/jobs/"
        update:
          path: "/jobs/"
        sendcsv:
          path: "/jobFile/upload"
      fieldPeriods:
        find:
          path: "/fieldPeriods/{fieldPeriod}"
